# Generated by Django 3.2.22 on 2023-10-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_created_on_addproduct_expires_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addpromotion',
            options={'ordering': ['-expires_on']},
        ),
        migrations.RenameField(
            model_name='addproduct',
            old_name='expires_on',
            new_name='added_on',
        ),
        migrations.RenameField(
            model_name='addpromotion',
            old_name='created_on',
            new_name='expires_on',
        ),
    ]
