# Generated by Django 3.2.22 on 2023-10-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20231030_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=300)),
                ('phone_number', models.CharField(max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
