# Generated by Django 3.2.22 on 2023-11-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_appuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
