# Generated by Django 3.2.22 on 2023-11-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_favouriteselection_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='know_more_products',
            new_name='i_want_to_know_more_about_the_products',
        ),
    ]
